# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # Das hier stellt sicher, dass alle Pods die gleiche iOS-Version nutzen
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # Verhindert Fehler bei Apple Silicon Simulatoren
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end

  %w[Pods-Runner].each do |target_name|
    %w[debug release].each do |config_name|
      xcconfig_path = File.join(installer.sandbox.root.to_s, 'Target Support Files', target_name, "#{target_name}.#{config_name}.xcconfig")
      next unless File.exist?(xcconfig_path)

      contents = File.read(xcconfig_path)
      force_load_sim = '-force_load "$(PODS_ROOT)/../.symlinks/plugins/h3_flutter/darwin/Libs/h3.xcframework/ios-arm64_x86_64-simulator/libh3.a"'
      force_load_ios = '-force_load "$(PODS_ROOT)/../.symlinks/plugins/h3_flutter/darwin/Libs/h3.xcframework/ios-arm64/libh3.a"'

      if contents.include?(force_load_sim) && contents.include?(force_load_ios)
        next
      end

      contents = contents.gsub(/^(OTHER_LDFLAGS = .*)$/) do |match|
        out = match
        out += "\nOTHER_LDFLAGS[sdk=iphonesimulator*] = $(inherited) #{force_load_sim}" unless contents.include?(force_load_sim)
        out += "\nOTHER_LDFLAGS[sdk=iphoneos*] = $(inherited) #{force_load_ios}" unless contents.include?(force_load_ios)
        out
      end
      File.write(xcconfig_path, contents)
    end
  end
end
